# Generated by Django 4.2.1 on 2023-06-02 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='img1',
            field=models.ImageField(upload_to='pics1'),
        ),
    ]
